defmodule Api.AuthTest do
  use Api.DataCase, async: true

  alias Api.Auth

  describe "verify_internal_token/1" do
    test "validates a token generated by generate_internal_token" do
      user = insert(:user)
      token = Auth.generate_internal_token(user)

      assert {:ok, claims} = Auth.verify_internal_token(token)
      assert claims["sub"] == to_string(user.id)
      assert claims["email"] == user.email
    end

    test "rejects invalid token" do
      assert {:error, :invalid_token} = Auth.verify_internal_token("invalid.token.here")
    end
  end

  describe "generate_internal_token/1" do
    test "generates a JWT with user claims" do
      user = insert(:user)
      token = Auth.generate_internal_token(user)

      assert is_binary(token)
      assert String.contains?(token, ".")
    end
  end
end
